### DISCUSSION TITLE
Not able to see metrics exported by mlpipeline-metrics.json

### DISCUSSION THREAD

**Discussion by lucasg1** [elyra-ai/elyra#2954] [Pipeline Editor/ Kubeflow Pipelines + Apache Airflow]
Hi everyone!

I have a notebook that is creating the mlpipeline-metrics.json file as follows (just like the [documentation](https://elyra.readthedocs.io/en/stable/recipes/visualizing-output-in-the-kfp-ui.html#visualizing-scalar-performance-metrics-in-the-kubeflow-pipelines-ui)):

```
metrics = {
    'metrics': [
        {
            'name': 'accuracy-score',
            'numberValue':  val_acc,
            'format': 'PERCENTAGE'
        },
        {
            'name': 'loss-score',
            'numberValue':  val_loss,
            'format': 'RAW'
        }
    ]
}

with open('mlpipeline-metrics.json', 'w') as f:
    json.dump(metrics, f)
```
But the thing is that I can't see the metrics at the Runs tab, I can only see that there is a Output Artifact called mlpipeline-metrics.json but I can see them anywhere:

![image](https://user-images.githubusercontent.com/18517054/194148543-a69783e8-13e3-4698-990c-1a635837126a.png)

Run output tab with nothing in it:

![image](https://user-images.githubusercontent.com/18517054/194148630-2b0b36b7-bec0-41f7-b932-8d637e52ca29.png)

In this same pipeline I'm creating a confusion matrix which I can see only in Visualizations tab clicking on the specific pipeline step, but not in the Run Output (should it be shown at the Run Output tab?):

![image](https://user-images.githubusercontent.com/18517054/194148776-fd609664-424b-415c-89a0-b54d6095a6a6.png)

- How to make metrics show at Run Output (or anywhere)?
- How to make the confusion matrix shows at Run Output and not only in Visualizations tab?

I'm pasting here some screenshots so it's easier to understand and also the log file from the last pipeline step, appreciate any help.

Obs: the variables val_acc and val_loss are defined:
![image](https://user-images.githubusercontent.com/18517054/194150023-ae5ebfd1-5234-4f05-8500-254abf57a1f5.png)

Log file: [log.txt](https://github.com/elyra-ai/elyra/files/9718569/log.txt)

The mlpipeline-metrics.json final file just in case: 
[mlpipeline-metrics.json.txt](https://github.com/elyra-ai/elyra/files/9718620/mlpipeline-metrics.json.txt)

**Comment by ptitzler** [comment]
Hi @lucasg1 !

As far as I know the only place where you can see these metrics is in the Experiments/runs view:


![image](https://user-images.githubusercontent.com/13068832/194171450-cdc797f0-5049-47d3-9e61-19a1a81835ee.png)

I had to look it up because it's been a while: https://www.kubeflow.org/docs/components/pipelines/v1/sdk/output-viewer/#introduction
If I recall the underlying idea is that in this view you can see multiple runs at once and it's easier to see wether there's any improvement to the metrics.

**Reply by lucasg1** [reply]
I can't find the metrics in the Experiments view also:
![image](https://user-images.githubusercontent.com/18517054/194319348-617ad533-9de3-42b1-a96b-d028d4020031.png)

And these metrics should appear in the Visualizations tab also, which is not the case (I just find the confusion matrix). Maybe I'm doing something wrong and I can't find what it is...

When I compare 2 runs, there are no metrics at all:

![image](https://user-images.githubusercontent.com/18517054/194319653-6d11f5aa-1a65-455c-822f-8e26f1eb9eaa.png)

**Reply by ptitzler** [reply]
Which version of Kubeflow Pipelines are you using?

**Reply by lucasg1** [reply]
I believe it's **2.0.0-alpha.3**, though I'm not sure...

I git cloned the https://github.com/kubeflow/manifests repository (in October 3) and installed everything with the command:

`while ! kustomize build example | kubectl apply -f -; do echo "Retrying to apply resources"; sleep 10; done`

The only way I found to find out the version was to print the _manifests/apps/pipeline/upstream/base/pipeline/kustomization.yaml_ file. But that still doesn't say what is the current running version. Is there a way to see the running Kubeflow Pipelines version?

kustomization.yaml file:

```
~/manifests/apps/pipeline/upstream$ cat base/pipeline/kustomization.yaml 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - metadata-writer
resources:
  - ml-pipeline-apiserver-deployment.yaml
  - ml-pipeline-apiserver-role.yaml
  - ml-pipeline-apiserver-rolebinding.yaml
  - ml-pipeline-apiserver-sa.yaml
  - ml-pipeline-apiserver-service.yaml
  - ml-pipeline-persistenceagent-deployment.yaml
  - ml-pipeline-persistenceagent-role.yaml
  - ml-pipeline-persistenceagent-rolebinding.yaml
  - ml-pipeline-persistenceagent-sa.yaml
  - ml-pipeline-scheduledworkflow-deployment.yaml
  - ml-pipeline-scheduledworkflow-role.yaml
  - ml-pipeline-scheduledworkflow-rolebinding.yaml
  - ml-pipeline-scheduledworkflow-sa.yaml
  - ml-pipeline-ui-deployment.yaml
  - ml-pipeline-ui-configmap.yaml
  - ml-pipeline-ui-role.yaml
  - ml-pipeline-ui-rolebinding.yaml
  - ml-pipeline-ui-sa.yaml
  - ml-pipeline-ui-service.yaml
  - ml-pipeline-viewer-crd-role.yaml
  - ml-pipeline-viewer-crd-rolebinding.yaml
  - ml-pipeline-viewer-crd-deployment.yaml
  - ml-pipeline-viewer-crd-sa.yaml
  - ml-pipeline-visualization-deployment.yaml
  - ml-pipeline-visualization-sa.yaml
  - ml-pipeline-visualization-service.yaml
  - pipeline-runner-role.yaml
  - pipeline-runner-rolebinding.yaml
  - pipeline-runner-sa.yaml
  - container-builder-sa.yaml
  - viewer-sa.yaml
  - kfp-launcher-configmap.yaml
images:
  - name: gcr.io/ml-pipeline/api-server
    newTag: 2.0.0-alpha.3
  - name: gcr.io/ml-pipeline/persistenceagent
    newTag: 2.0.0-alpha.3
  - name: gcr.io/ml-pipeline/scheduledworkflow
    newTag: 2.0.0-alpha.3
  - name: gcr.io/ml-pipeline/frontend
    newTag: 2.0.0-alpha.3
  - name: gcr.io/ml-pipeline/viewer-crd-controller
    newTag: 2.0.0-alpha.3
  - name: gcr.io/ml-pipeline/visualization-server
    newTag: 2.0.0-alpha.3

```
