### DISCUSSION TITLE
Supported datatypes for custom component connectors

### DISCUSSION THREAD

**Discussion by savemuri** [elyra-ai/elyra#3217] [Pipeline Editor/ Kubeflow Pipelines + Apache Airflow]
I am experimenting with custom component connectors and noticed that the field types are getting rendered as `oneOf` type in the UI. I went over docs and did not find any references on how I can render different field types like file upload widget etc.

Is this a known limitation with using custom components?

```
name: Run My Node
description: Run Node.
inputs:
- {name: Notebook, optional: false, type: JupyterNotebook, description: 'Required. Notebook to execute.'}
- {name: TestField, optional: false, type: file, description: 'Test field.'}
outputs:
- {name: Notebook, type: JupyterNotebook, description: 'Executed notebook.'}
- {name: Output data, description: 'Directory with any output data. In notebook, the OUTPUT_DATA_PATH variable will point to this directory, so that the notebook can write output data there.'}
metadata:
  annotations:
    author: name
implementation:
  container:
    image: python:3.7
    command:
    - sh
    - -exc
    - |
      input_notebook_path="$0"
      output_notebook_path="$1"
      arguments="$2"
      packages_to_install="$3"
      input_data_path="$4"
      output_data_path="$5"
      mkdir -p "$(dirname "$output_notebook_path")"
      mkdir -p "$output_data_path"

      # Converting packages_to_install from JSON to command-line arguments
      packages_to_install=$(echo "$packages_to_install" | sed -E -e 's/^\[//' -e 's/]$//' -e 's/",/" /g' -e "s/\"/'/g")
      # Installing packages
      sh -c "python3 -m pip install --upgrade --quiet jupyter papermill==2.2.0 ${packages_to_install}"
      # Running the notebook using papermill
      papermill --parameters_yaml "$arguments" --parameters INPUT_DATA_PATH "$input_data_path" --parameters OUTPUT_DATA_PATH "$output_data_path" "$input_notebook_path" "$output_notebook_path"
      
    - {inputPath: Notebook}
    - {outputPath: Notebook}
    - {inputValue: Parameters}
    - if:
        cond: {isPresent: Packages to install}
        then: [{inputValue: Packages to install}]
        else: "{}"
    - {outputPath: Output data}
```
