### ISSUE TITLE
[RFC] Node schema for pipelines 2.0

### ISSUE THREAD

**Issue by bourdakos1** [elyra-ai/elyra#1444]
Our current solution for handling palette and node properties needs to be overhauled in order to support pipeline 2.0 features.

## Current solution
- a hard-coded `palette.json` on the frontend with a fixed list of available nodes and their associated metadata
- a hard-coded `properties.json` on the fronted with a single instance of `CommonProperties` properties that is assumed to be use for all nodes in the palette
- validation of nodes is also hard-coded and doesn't use `properties.json` so if `properties.json` changes, the validation needs to be updated as well

## Requirements
- we should not assume a fixed set of nodes
- we should have the ability to lock node types to a specific runtime
- each node type should be able to have its own properties definition
- runtimes should be able to add properties to nodes
- we need to keep the ability of affiliating a filetype with a node type (this enables dragging and dropping files onto the pipeline)
- we should support dynamic node labels where the node type can decide whether to show the file name a fixed label or something else as the label
- we should support dynamic properties (properties can vary based on the node itself, not just the node type)

we might want a way to generate a component based on a url?

## Proposal
Instead of the concept of a single "palette" and single "properties", introduce the idea of a "node schema" per node type. This collection of "node schema" will be used to generate a palette at runtime. A runtime should still be able to provide "properties" that is applied across all nodes. Properties will initially only be validated for type, requiredness, regex, min/max and other various json schema specs. All other property validation should be done at submission time.

A "node schema" should contain all static metadata needed for a node:
- `op` (the ID for a node type, ie `execute-notebook-node` / `execute-python-node`)
- `image` (svg that will show up on the node)
- `label` (the default label, since this can be dynamic)
- `description` (the description that could show up in the palette or when hovering on the node in the pipeline)
- `properties` (the fixed properties for the node. dynamic and runtime specific properties don't go here)

A "node schema" should also be able to specify that it is "file based":
- `fileBased` (boolean)
- `extensions` (valid extensions for the node. if more than one node spec requests a given extension we should add a dropdown property to manually choose the node's type or prompt the user to choose onDrop)
- (this will attach a property for `filename`)
- (this will be the only field that can be validated for a file's existence at runtime)

A "node schema" should have a fixed "label" property so that the user can manually adjust the label. The winning label would follow the logic of: `node.properties.label ?? node.properties.filename ?? node.label`

### Properties
The finalized properties of a node will be generated from:
- filename (if `fileBased` is true)
- label
- static properties defined in "node schema"
- dynamic node specific properties
- global runtime properties (do we need more granularity than global?)

Properties should be a superset of JSON Schema/openapi (but we should support common properties, but note that it is not recommend and could have issues) 

## Examples
POC for being able to drag and drop any arbitrary KFP yaml component onto a pipeline.

Node schema:
```js
{
  op: "execute-kfp-component",
  fileBased: true,
  extensions: [".yaml", ".yml"],
  image: "xxx",
  label: "KFP Component",
  description: "A KubeFlow Pipelines YAML component",
  properties: []
}
```

KFP Component yaml: (I am assuming inputs are what would be turned into properties?, not sure how outputs would be handled)
```yaml
name: 'Deploy Model - Watson Machine Learning'
description: |
  Deploy stored model on Watson Machine Learning as a web service.
metadata:
  annotations: {platform: 'IBM Watson Machine Learning'}
inputs:
  - {name: model_uid,        description: 'Required. UID for the stored model on Watson Machine Learning'}
  - {name: model_name,       description: 'Required. Model Name on Watson Machine Learning'}
  - {name: scoring_payload,  description: 'Sample Payload file name in the object storage', default: ''}
  - {name: deployment_name,  description: 'Deployment Name on Watson Machine Learning', default: ''}
outputs:
  - {name: scoring_endpoint, description: 'Link to the deployed model web service'}
  - {name: model_uid,        description: 'UID for the stored model on Watson Machine Learning'}
implementation:
  container:
    image: docker.io/aipipeline/wml-deploy:latest
    command: ['python']
    args: [
      -u, /app/wml-deploy.py,
      --model-uid, {inputValue: model_uid},
      --model-name, {inputValue: model_name},
      --scoring-payload, {inputValue: scoring_payload},
      --deployment-name, {inputValue: deployment_name},
      --output-scoring-endpoint-path, {outputPath: scoring_endpoint},
      --output-model-uid-path, {outputPath: model_uid}
    ]
```

Runtime properties:
```
cpu:
  type: number
gpu:
  type: number
memory:
  type: number
```

finalized properties based on above:
```yaml
filename:
  type: string
  description: The path to the file.
  required: true
label:
  type: string
  description: The label for the node.
model_uid:
  type: string
  description: Required. UID for the stored model on Watson Machine Learning
model_name:
  type: string
  description: Required. Model Name on Watson Machine Learning
scoring_payload:
  type: string
  description: Sample Payload file name in the object storage
  default: ""
deployment_name:
  type: string
  description: Deployment Name on Watson Machine Learning
  default: ""
cpu:
  type: number
gpu:
  type: number
memory:
  type: number
```
