### ISSUE TITLE
Elyra installation on Jupyterhub: "Error contacting server - Endpoint elyra/namespace not found"

### ISSUE THREAD

**Issue by marcelbo2021** [elyra-ai/elyra#1474]
**Describe the issue**
I installed Elyra on an Azure Kubernetes Cluster following the official instructions.
The installation process itself went well but when opening the public IP of the service "proxy-public" in my browser and after having logged in, I encounter the following error message: "Error contacting server - Endpoint elyra/namespace not found"

**To Reproduce**
1. Setup Azure Kubernetes Cluster
2. Install JupyterHub according to https://zero-to-jupyterhub.readthedocs.io/en/stable/jupyterhub/installation.html (version 0.10.6)
3. Go to https://elyra.readthedocs.io/en/latest/recipes/deploying-elyra-in-a-jupyterhub-environment.html, install Jupyter Enterprise Gateway and adjust config.yaml accordingly:
```
# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
#
proxy:
  secretToken: "****"
hub:
  config:
    Authenticator:
      admin_users:
        - admin
    DummyAuthenticator:
      password: ******
    JupyterHub:
      authenticator_class: dummy
  extraConfig: |-
    from kubespawner import KubeSpawner
    from tornado import gen
    import yaml

    class CustomKubeSpawner(KubeSpawner):
        def get_env(self):
            env = super().get_env()

            env['KERNEL_USERNAME'] =  self.user.name

            return env
    c.JupyterHub.spawner_class = CustomKubeSpawner
    c.Spawner.start_timeout = 500

singleuser:
  defaultUrl: "/lab"
  image:
    name: elyra/elyra
    # change to a specific release version as appropriated
    tag: dev
    # disable this in a production environment
    pullPolicy: "Always"
  storage:
    dynamic:
      storageClass: default
  extraEnv:
    JUPYTER_GATEWAY_URL: 10.244.*.*:8888
    JUPYTER_GATEWAY_REQUEST_TIMEOUT: "120"

```
3. Go to public IP of the service "proxy-public" and login using DummyAuthenticator password defined above.

**Screenshots or log output**
![Capture](https://user-images.githubusercontent.com/81307664/112316273-d9b46180-8ca2-11eb-99ed-cde0180afa44.PNG)

**Expected behavior**
Elyra ready to be used without any error message

**Deployment information**
 - Helm deployment of JupyterHub: `helm upgrade --cleanup-on-fail --install jhub jupyterhub/jupyterhub --namespace jhub --create-namespace --version=0.10.6 --values config.yaml`
 - Jupyter Enterprise Gateway deployment: `kubectl apply -f https://raw.githubusercontent.com/jupyter/enterprise_gateway/v2.1.1/etc/kubernetes/enterprise-gateway.yaml`
 - Operating system: Ubuntu
 - Installation source: official container image
 - Deployment type: Kubernetes
