### ISSUE TITLE
No Kernel available in Elyra installation on JupyterHub using Azure Kubernetes

### ISSUE THREAD

**Issue by marcelbo2021** [elyra-ai/elyra#1565]
**Describe the issue**
I installed Elyra on an Azure Kubernetes Cluster following the official instructions.
However, there is no Kernel to choose from in the User Interface (see screenshot below), when I create a new notebook which shall use the Python 3 Kernel although it is apparently correctly installed (see other screenshot below). I tried this both with Firefox and Edge.

**To Reproduce**
1. Setup Azure Kubernetes Cluster
2. Install JupyterHub according to https://zero-to-jupyterhub.readthedocs.io/en/stable/jupyterhub/installation.html (version 0.10.6)
3. Go to https://elyra.readthedocs.io/en/latest/recipes/deploying-elyra-in-a-jupyterhub-environment.html, install Jupyter Enterprise Gateway and adjust config.yaml accordingly:
```
# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
#
proxy:
  secretToken: "****"
hub:
  config:
    Authenticator:
      admin_users:
        - admin
    DummyAuthenticator:
      password: ******
    JupyterHub:
      authenticator_class: dummy
  extraConfig: |-
    from kubespawner import KubeSpawner
    from tornado import gen
    import yaml

    class CustomKubeSpawner(KubeSpawner):
        def get_env(self):
            env = super().get_env()

            env['KERNEL_USERNAME'] =  self.user.name

            return env
    c.JupyterHub.spawner_class = CustomKubeSpawner
    c.Spawner.start_timeout = 500

singleuser:
  defaultUrl: "/lab"
  image:
    name: elyra/elyra
    # change to a specific release version as appropriated
    tag: dev
    # disable this in a production environment
    pullPolicy: "Always"
  storage:
    dynamic:
      storageClass: default
  extraEnv:
    JUPYTER_GATEWAY_URL: 10.244.*.*:8888
    JUPYTER_GATEWAY_REQUEST_TIMEOUT: "120"

```
3. Go to public IP of the service "proxy-public" and login using DummyAuthenticator password defined above.
4. Create a new Jupyter notebook (File -> New -> Notebook)
5. Try to configure a Kernel for the notebook and note that there is no option to choose from in the drop-down menu

**Screenshots or log output**
![kernel](https://user-images.githubusercontent.com/81307664/114693854-85ccf380-9d09-11eb-866d-c22cd8584a6b.PNG)
![kernelinstall](https://user-images.githubusercontent.com/81307664/114695011-a8134100-9d0a-11eb-9337-ecc8d5f29d06.PNG)

**Expected behavior**
I expect to be able to choose the Python 3 Kernel in the "Select Kernel" window.

**Deployment information**
 - Helm deployment of JupyterHub: `helm upgrade --cleanup-on-fail --install jhub jupyterhub/jupyterhub --namespace jhub --create-namespace --version=0.10.6 --values config.yaml`
 - Jupyter Enterprise Gateway deployment: `kubectl apply -f https://raw.githubusercontent.com/jupyter/enterprise_gateway/v2.1.1/etc/kubernetes/enterprise-gateway.yaml`
 - Operating system: Ubuntu
 - Installation source: official container image
 - Deployment type: Kubernetes

**Comment by ptitzler** [comment]
Quick side note - the example snippet in our documentation references the `elyra/elyra:dev` container image, which isn't necessarily based on a stable build. Could you please change the `dev` tag to either `2.2.1` or `latest` (latest stable version, which as of today is `2.2.1`) to get a more predictable result. 

```
singleuser:
  defaultUrl: "/lab"
  image:
    name: elyra/elyra
    # change to a specific release version as appropriated
    tag: dev
```

Suggested:

```
singleuser:
  defaultUrl: "/lab"
  image:
    name: elyra/elyra
    # change to a specific release version as appropriated
    tag: 2.2.1
```


@akchinSTC @lresende we should probably update the doc to use `latest` instead
