### ISSUE TITLE
Filepath handling for generic and custom components

### ISSUE THREAD

**Issue by bourdakos1** [elyra-ai/elyra#1991]
How to handle conversion of properties with paths: pipeline-relative -> workspace-relative

-more info coming soon-

**Comment by bourdakos1** [comment]
## Example

file system:
```
a
`- b
   `- c
      `- d
         |- example.pipeline
         `- scripts
            |- example.py
            `- in.txt
```


`persisted`: (workdir: N/A)
```diff
filename: "scripts/example.py",
dependencies: ["in.txt"],
outputs: ["out.txt"]
```

`persisted` -> `UI time`: (workdir: "/a/b")
```diff
filename: "scripts/example.py",
dependencies: ["in.txt"],
outputs: ["out.txt"]
```

`UI time` -> `submission API`: (workdir: "/a/b")
```diff
- filename: "scripts/example.py"
+ filename: "c/d/scripts/example.py",
dependencies: ["in.txt"],
outputs: ["out.txt"]
```

**Comment by bourdakos1** [comment]
After some discussion, we have come up with a possible solution of introducing "property types". Each property could _ALWAYS_ either be a file, raw data, or output from another node (the type of property would be determined by the user not the component). The UI would display a special input control for each property that would let the user choose to use a file picker, enter raw data manually (this would still show things like a checkbox for a boolean type), or choose an output coming from an ancestor node.

The short term solution will be to use inputPath/inputValue to determine if a property will be a "file", _NOT_ type. We can then safely transform the path to be relative to the workspace during submission.

**Comment by bourdakos1** [comment]
## Short term examples

The following would generate 1 property, `example`, with a type of `file`
It would probably be easier for a user to use a checkbox interface in common properties, but they would be required to use a file picker to choose a file that contains text that can be serialized to boolean:
```yaml
name: Demo1
inputs:
- {name: Example, type: Bool}
implementation:
  container:
    image: alpine
    command:
    - sh
    - -ec
    - |
      example=$0
      echo "$example"
    - {inputPath: Example}
```


The following would generate 1 property, `example`, with a type of `string`
It would probably be easier for a user to use a file picker to choose a Jupyter Noteboook, but a user would be required to enter the entire Jupyter Notebook JSON contents as a string:
```yaml
name: Demo2
inputs:
- {name: Example, type: JupyterNotebook}
implementation:
  container:
    image: alpine
    command:
    - sh
    - -ec
    - |
      example=$0
      echo "$example"
    - {inputValue: Example}
```
