### ISSUE TITLE
set Notebook/Script environment variables from upstream outputs

### ISSUE THREAD

**Issue by thesuperzapper** [elyra-ai/elyra#2472]
## Background 

After PR https://github.com/elyra-ai/elyra/pull/2350, users can now consume the `outputPath`'s from parent nodes as `inputValues`, but this feature can't be used by the generic Notebook/Script nodes. 

I think the most generic way of passing these outputs to the notebook is using environment variables.

## UI Implementation

We would add something similar to the `"Please select an output from a parent: "` but to the environment variable setter.

![Screen Shot 2022-02-10 at 21 18 16](https://user-images.githubusercontent.com/5735406/153386651-29c79b8a-5b25-47a0-bdb5-e0560f05226d.png)

![Screen Shot 2022-02-10 at 21 17 16](https://user-images.githubusercontent.com/5735406/153386472-4ad70715-6439-4987-92b1-9307d7e5e7ba.png)

## Argo Implementation

We can set the `env` field from the parent's Argo parameters using `{{steps.STEP_NAME.outputs.parameters.PARAM_NAME}}`:

___NOTE:__ this example actually passes an "input" using the method proposed in https://github.com/elyra-ai/elyra/issues/2471, rather than an "output"_

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-parameter-
spec:
  entrypoint: lambda
  templates:
    - name: lambda
      dag:
        tasks:
          - name: parent-node
            template: parent-node

          - name: notebook-node
            template: notebook-node
            dependencies: [parent-node]
            arguments:
              parameters:
                - name: message
                  value: "{{steps.parent-node.outputs.parameters.message}}"

    - name: parent-node
      inputs:
        parameters:
          - name: message
      container:
        ...
      outputs:
        parameters:
          - name: message
            value: "{{inputs.parameters.message}}"

    - name: notebook-node
      inputs:
        parameters:
          - name: message
      container:
        args: [...]
        command: [...]
        image: "..."
        env:
          - name: MESSAGE_ENV_VAR
            value: "{{inputs.parameters.message}}"
```
