### ISSUE TITLE
use `black` formatter on elyra's python code

### ISSUE THREAD

**Issue by thesuperzapper** [elyra-ai/elyra#2542]
Currently, we have relatively haphazard and inconsistent formatting across our python code. The industry is largely converging on the [`black` formatter](https://github.com/psf/black), which automatically formats Python code into a [highly consistent style](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html). I propose that we start using black with elyra.

## Steps to try black on Elyra:

1. Install black from pip:
    ```bash
    pip install black
    ```
3. Create a file at the root of the elyra repo called `pyproject.toml` with these contents:
     ```toml
     [tool.black]
    # you can play around with line-length to see what you think suits elyra best
    # black defaults to 88, but projects often chose larger values (for example, airflow uses 110)
    line-length = 110

    # this tells black what features of python can be used to clean up code 
    # targeting 'py37' ensures we support python 3.7
    target-version = ['py37', 'py38', 'py39']
    ```
4. `cd` into the root of the elyra folder and run:
    ```bash
    # WARNING: make sure you haven't got any uncommitted changes, as this will reformat ALL files!
    black .
    ```

## Proposal to implement black

1. Agree on a `line-length`
2. Reformat all python code in a single commit ([recommended by black](https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html))
    - NOTE: formatting can be disabled for a section by wrapping it in `# fmt: off` and then `# fmt: on`
4. Add black to the `lint-server` maven target (so that it fails if black would reformat the code):
    - `black --check --diff --color .`
6. Ensure [`.github/workflows/build.yml`](https://github.com/elyra-ai/elyra/blob/master/.github/workflows/build.yml) fails if black would reformat the code (this prevents unformatted code being merged in PRs)
7. Update the ["contributing to elyra"](https://elyra.readthedocs.io/en/latest/developer_guide/contributing.html) docs with information about black and its [editor intergration](https://black.readthedocs.io/en/stable/integrations/editors.html)
8. Consider using [pre-commit](https://pre-commit.com/) to help users automatically format before git commiting (see [the black documentation on pre-commit](https://black.readthedocs.io/en/stable/integrations/source_version_control.html))
