### ISSUE TITLE
(Question) Do I have to make new K8s Service Account Token in every 2 hours??

### ISSUE THREAD

**Issue by kimkihoon0515** [elyra-ai/elyra#3089]
![image](https://user-images.githubusercontent.com/63439911/214560806-9c8ee144-39b3-4d45-b843-56b5241a1ac2.png)
I used Kubernetes Service Token for the authentication.
I made a poddefault config like this
```
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: access-ml-pipeline
  namespace: "<YOUR_USER_PROFILE_NAMESPACE>"
spec:
  desc: Allow access to Kubeflow Pipelines
  selector:
    matchLabels:
      access-ml-pipeline: "true"
  env:
    - ## this environment variable is automatically read by `kfp.Client()`
      ## this is the default value, but we show it here for clarity
      name: KF_PIPELINES_SA_TOKEN_PATH
      value: /var/run/secrets/kubeflow/pipelines/token
  volumes:
    - name: volume-kf-pipeline-token
      projected:
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 7200
              ## defined by the `TOKEN_REVIEW_AUDIENCE` environment variable on the `ml-pipeline` deployment
              audience: pipelines.kubeflow.org      
  volumeMounts:
    - mountPath: /var/run/secrets/kubeflow/pipelines
      name: volume-kf-pipeline-token
      readOnly: true
```
But it seems doesn't work anymore.
I guess it's because of the expirationSeconds which is set to 7200 sec so that I have to remake the token for authentication.
Is it right? 

Plus the default token didn't work. 
What i did is I replaced the token which placed in **/var/run/secrets/kubeflow/pipelines** to authservice_session which i got from Kubeflow Central Dashboard like this.
![image](https://user-images.githubusercontent.com/63439911/214561913-e94ca6b1-cbb3-4e6d-9995-6726d1c1b5f1.png)

**Comment by ptitzler** [comment]
Hi @kimkihoon0515,

A few general questions: 

- Are you running Elyra as a notebook server in Kubeflow?
- Which version of Kubernetes and Kubeflow/Kubeflow Pipelines are you using?
- Does the user namespace value in your Elyra runtime configuration match the value you've specified as `<YOUR_USER_PROFILE_NAMESPACE>` in the poddefault yaml file?

Onto your questions:

> But it seems doesn't work anymore.

Can you clarify if this ever worked for you? Your wording appears to imply that it did.

> I guess it's because of the expirationSeconds which is set to 7200 sec so that I have to remake the token for authentication. Is it right?

The token does expire. It's the apps responsibility (in this case Kubeflow Pipelines) to refresh it, not yours. I found `https://github.com/kubeflow/kubeflow/issues/6484`, which might be relevant and therefore prompted me to ask for your Kubernetes version. I should note that there is nothing Elyra specific about this.

**Comment by kimkihoon0515** [comment]
@ptitzler 
- Are you running Elyra as a notebook server in Kubeflow?
Yes. I'm running Elyra with kf-notebook:latest image on Kubeflow.

- Which version of Kubernetes and Kubeflow/Kubeflow Pipelines are you using?
I'm using Kubernetes version 1.21.3 and 1.6.0/1.8.18 
- Does the user namespace value in your Elyra runtime configuration match the value you've specified as <YOUR_USER_PROFILE_NAMESPACE> in the poddefault yaml file?
heres a token.yaml file that I used.
```
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: access-ml-pipeline
  namespace: "kubeflow-user-example-com"
spec:
  desc: Allow access to Kubeflow Pipelines
  selector:
    matchLabels:
      access-ml-pipeline: "true"
  volumes:
    - name: volume-kf-pipeline-token
      projected:
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 7200
              audience: pipelines.kubeflow.org      
  volumeMounts:
    - mountPath: /var/run/secrets/kubeflow/pipelines
      name: volume-kf-pipeline-token
      readOnly: true
  env:
    - name: KF_PIPELINES_SA_TOKEN_PATH
      value: /var/run/secrets/kubeflow/pipelines/token
```
