### ISSUE TITLE
AWS access key are referenced in exported pipeline file

### ISSUE THREAD

**Issue by harshad16** [elyra-ai/elyra#3164]
**Describe the issue**

Exporting a pipeline from Elyra notebook pipeline editor as Python DSL or YAML reads S3 credentials from the cluster and saves them in plain text in the generated output. 

https://elyra.readthedocs.io/en/v3.9.0/user_guide/pipelines.html#exporting-pipelines

The Exported file has an AWS s3 credential, can this be masked or an option to set this from the pipeline, instead of exposing them on the pipeline would help users upload their pipeline publically on git?

Or just referencing it from Kubernetes secret could be another possible solution. 

**To Reproduce**
1. Go to export from elyra
2. Click on export the file as yaml
3. Scroll down in the yaml and view AWS keys

**Screenshots or log output**
In the YAML
```
spec:
  pipelineSpec:
    tasks:
    - name: data-prep
      taskSpec:
        steps:
        - name: main
          env:
          - name: AWS_SECRET_ACCESS_KEY
            value: value  
```

**Expected behavior**
In the YAML

```
spec:
  pipelineSpec:
    tasks:
    - name: data-prep
      taskSpec:
        steps:
        - name: main
          env:
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
               secretKeyRef: secret
```

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: [e.g. 1.5.3]: 3.15.0
 - Operating system: [e.g. macos, linux] : linux (ubi9)
 - Installation source: [e.g. PyPI, conda, from source, official container image, custom container image]: pypi
 - Deployment type: [e.g. local installation, Docker, Kubernetes, Kubeflow [notebook server] , Open Data Hub]: opendatahub

**Pipeline runtime environment**
If the issue is related to pipeline execution, identify the environment where the pipeline is executed
 - Kubeflow Pipelines (provide version number, whether multi-user auth enabled)

**Runtime configuration settings**
If the issue is related to pipeline execution, document the runtime configuration settings from the Elyra UI, omitting confidential information.
